// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_string
// @generated from protobuf file "user-consultant-service.proto" (package "com.hamro.jyotish", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserConsultantService } from "./user-consultant-service";
import type { SearchConsultantResponse } from "./user-consultant-service";
import type { SearchConsultantRequest } from "./user-consultant-service";
import type { GetAllOnlineConsultantResponse } from "./user-consultant-service";
import type { GetAllOnlineConsultantRequest } from "./user-consultant-service";
import type { Empty } from "./jyotish-common";
import type { GetAllConsultantResponse } from "./jyotish-common";
import type { GetAllConsultantRequest } from "./jyotish-common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Consultant } from "./jyotish-common";
import type { GetByIdRequest } from "./jyotish-common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service com.hamro.jyotish.UserConsultantService
 */
export interface IUserConsultantServiceClient {
    /**
     * @generated from protobuf rpc: GetConsultantById
     */
    getConsultantById(input: GetByIdRequest, options?: RpcOptions): UnaryCall<GetByIdRequest, Consultant>;
    /**
     * @generated from protobuf rpc: GetAllConsultant
     */
    getAllConsultant(input: GetAllConsultantRequest, options?: RpcOptions): UnaryCall<GetAllConsultantRequest, GetAllConsultantResponse>;
    /**
     * @generated from protobuf rpc: GetLegacyAllConsultant
     */
    getLegacyAllConsultant(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetAllConsultantResponse>;
    /**
     * @generated from protobuf rpc: GetAllOnlineConsultant
     */
    getAllOnlineConsultant(input: GetAllOnlineConsultantRequest, options?: RpcOptions): UnaryCall<GetAllOnlineConsultantRequest, GetAllOnlineConsultantResponse>;
    /**
     * @generated from protobuf rpc: SearchConsultant
     */
    searchConsultant(input: SearchConsultantRequest, options?: RpcOptions): UnaryCall<SearchConsultantRequest, SearchConsultantResponse>;
}
/**
 * @generated from protobuf service com.hamro.jyotish.UserConsultantService
 */
export class UserConsultantServiceClient implements IUserConsultantServiceClient, ServiceInfo {
    typeName = UserConsultantService.typeName;
    methods = UserConsultantService.methods;
    options = UserConsultantService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetConsultantById
     */
    getConsultantById(input: GetByIdRequest, options?: RpcOptions): UnaryCall<GetByIdRequest, Consultant> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetByIdRequest, Consultant>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllConsultant
     */
    getAllConsultant(input: GetAllConsultantRequest, options?: RpcOptions): UnaryCall<GetAllConsultantRequest, GetAllConsultantResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllConsultantRequest, GetAllConsultantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLegacyAllConsultant
     */
    getLegacyAllConsultant(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetAllConsultantResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetAllConsultantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllOnlineConsultant
     */
    getAllOnlineConsultant(input: GetAllOnlineConsultantRequest, options?: RpcOptions): UnaryCall<GetAllOnlineConsultantRequest, GetAllOnlineConsultantResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllOnlineConsultantRequest, GetAllOnlineConsultantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchConsultant
     */
    searchConsultant(input: SearchConsultantRequest, options?: RpcOptions): UnaryCall<SearchConsultantRequest, SearchConsultantResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchConsultantRequest, SearchConsultantResponse>("unary", this._transport, method, opt, input);
    }
}
