// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_string
// @generated from protobuf file "user-consultant-service.proto" (package "com.hamro.jyotish", syntax proto3)
// tslint:disable
import { Empty } from "./jyotish-common";
import { GetAllConsultantResponse } from "./jyotish-common";
import { GetAllConsultantRequest } from "./jyotish-common";
import { GetByIdRequest } from "./jyotish-common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Rating } from "./jyotish-common";
import { PresenceStatus } from "./jyotish-common";
import { Consultant } from "./jyotish-common";
/**
 * @generated from protobuf message com.hamro.jyotish.SearchConsultantRequest
 */
export interface SearchConsultantRequest {
    /**
     * @generated from protobuf field: string sku = 1
     */
    sku: string;
}
/**
 * @generated from protobuf message com.hamro.jyotish.SearchConsultantResponse
 */
export interface SearchConsultantResponse {
    /**
     * @generated from protobuf field: string next = 1
     */
    next: string;
    /**
     * @generated from protobuf field: repeated com.hamro.jyotish.ConsultantResponse items = 2
     */
    items: ConsultantResponse[];
}
/**
 * @generated from protobuf message com.hamro.jyotish.ConsultantResponse
 */
export interface ConsultantResponse {
    /**
     * @generated from protobuf field: com.hamro.jyotish.Consultant consultant_response = 1
     */
    consultantResponse?: Consultant;
    /**
     * @generated from protobuf field: com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus timed_presence_status = 2
     */
    timedPresenceStatus?: ConsultantResponse_TimedPresenceStatus;
}
/**
 * @generated from protobuf message com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus
 */
export interface ConsultantResponse_TimedPresenceStatus {
    /**
     * @generated from protobuf field: com.hamro.jyotish.PresenceStatus presence_status = 1
     */
    presenceStatus: PresenceStatus;
    /**
     * @generated from protobuf field: int64 timestamp = 2
     */
    timestamp: string;
}
/**
 * @generated from protobuf message com.hamro.jyotish.GetAllOnlineConsultantResponse
 */
export interface GetAllOnlineConsultantResponse {
    /**
     * @generated from protobuf field: repeated com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus list = 1
     */
    list: GetAllOnlineConsultantResponse_ConsultantStatus[];
    /**
     * @generated from protobuf field: string productSKU = 2
     */
    productSKU: string;
    /**
     * @generated from protobuf field: string next_page_cursor = 3
     */
    nextPageCursor: string;
    /**
     * new
     *
     * @generated from protobuf field: repeated com.hamro.jyotish.OnlineConsultant consultants = 4
     */
    consultants: OnlineConsultant[];
}
/**
 * @generated from protobuf message com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus
 */
export interface GetAllOnlineConsultantResponse_ConsultantStatus {
    /**
     * @generated from protobuf field: com.hamro.jyotish.Consultant consultant = 1
     */
    consultant?: Consultant;
    /**
     * @generated from protobuf field: com.hamro.jyotish.PresenceStatus presence = 2
     */
    presence: PresenceStatus;
    /**
     * @generated from protobuf field: int64 no_of_reviews = 3
     */
    noOfReviews: string;
}
/**
 * @generated from protobuf message com.hamro.jyotish.GetAllOnlineConsultantRequest
 */
export interface GetAllOnlineConsultantRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string productSKU = 2
     */
    productSKU: string;
    /**
     * @generated from protobuf field: string next_page_token = 3
     */
    nextPageToken: string;
    /**
     * @generated from protobuf field: int32 limit = 4
     */
    limit: number;
}
/**
 * @generated from protobuf message com.hamro.jyotish.OnlineConsultant
 */
export interface OnlineConsultant {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string image = 3
     */
    image: string;
    /**
     * @generated from protobuf field: string bio = 4
     */
    bio: string;
    /**
     * @generated from protobuf field: int64 rating_count = 5
     */
    ratingCount: string;
    /**
     * @generated from protobuf field: com.hamro.jyotish.Rating rating = 6
     */
    rating?: Rating;
    /**
     * @generated from protobuf field: string intro = 7
     */
    intro: string;
    /**
     * @generated from protobuf field: com.hamro.jyotish.PresenceStatus presence_status = 8
     */
    presenceStatus: PresenceStatus;
    /**
     * @generated from protobuf field: string title = 9
     */
    title: string;
    /**
     * @generated from protobuf field: int64 total_call_duration = 10
     */
    totalCallDuration: string;
    /**
     * @generated from protobuf field: double average_rating = 11
     */
    averageRating: number;
    /**
     * @generated from protobuf field: int64 joining_since = 12
     */
    joiningSince: string;
    /**
     * @generated from protobuf field: int32 years_of_experience = 13
     */
    yearsOfExperience: number;
    /**
     * @generated from protobuf field: string profile_banner = 14
     */
    profileBanner: string;
    /**
     * @generated from protobuf field: string video = 15
     */
    video: string;
    /**
     * @generated from protobuf field: string thumbnail_url = 16
     */
    thumbnailUrl: string;
    /**
     * @generated from protobuf field: string aspect_ratio = 17
     */
    aspectRatio: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SearchConsultantRequest$Type extends MessageType<SearchConsultantRequest> {
    constructor() {
        super("com.hamro.jyotish.SearchConsultantRequest", [
            { no: 1, name: "sku", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchConsultantRequest>): SearchConsultantRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sku = "";
        if (value !== undefined)
            reflectionMergePartial<SearchConsultantRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchConsultantRequest): SearchConsultantRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string sku */ 1:
                    message.sku = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchConsultantRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string sku = 1; */
        if (message.sku !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sku);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.SearchConsultantRequest
 */
export const SearchConsultantRequest = new SearchConsultantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchConsultantResponse$Type extends MessageType<SearchConsultantResponse> {
    constructor() {
        super("com.hamro.jyotish.SearchConsultantResponse", [
            { no: 1, name: "next", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ConsultantResponse }
        ]);
    }
    create(value?: PartialMessage<SearchConsultantResponse>): SearchConsultantResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.next = "";
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<SearchConsultantResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchConsultantResponse): SearchConsultantResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string next */ 1:
                    message.next = reader.string();
                    break;
                case /* repeated com.hamro.jyotish.ConsultantResponse items */ 2:
                    message.items.push(ConsultantResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchConsultantResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string next = 1; */
        if (message.next !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.next);
        /* repeated com.hamro.jyotish.ConsultantResponse items = 2; */
        for (let i = 0; i < message.items.length; i++)
            ConsultantResponse.internalBinaryWrite(message.items[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.SearchConsultantResponse
 */
export const SearchConsultantResponse = new SearchConsultantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConsultantResponse$Type extends MessageType<ConsultantResponse> {
    constructor() {
        super("com.hamro.jyotish.ConsultantResponse", [
            { no: 1, name: "consultant_response", kind: "message", T: () => Consultant },
            { no: 2, name: "timed_presence_status", kind: "message", T: () => ConsultantResponse_TimedPresenceStatus }
        ]);
    }
    create(value?: PartialMessage<ConsultantResponse>): ConsultantResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ConsultantResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConsultantResponse): ConsultantResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* com.hamro.jyotish.Consultant consultant_response */ 1:
                    message.consultantResponse = Consultant.internalBinaryRead(reader, reader.uint32(), options, message.consultantResponse);
                    break;
                case /* com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus timed_presence_status */ 2:
                    message.timedPresenceStatus = ConsultantResponse_TimedPresenceStatus.internalBinaryRead(reader, reader.uint32(), options, message.timedPresenceStatus);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConsultantResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* com.hamro.jyotish.Consultant consultant_response = 1; */
        if (message.consultantResponse)
            Consultant.internalBinaryWrite(message.consultantResponse, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus timed_presence_status = 2; */
        if (message.timedPresenceStatus)
            ConsultantResponse_TimedPresenceStatus.internalBinaryWrite(message.timedPresenceStatus, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.ConsultantResponse
 */
export const ConsultantResponse = new ConsultantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConsultantResponse_TimedPresenceStatus$Type extends MessageType<ConsultantResponse_TimedPresenceStatus> {
    constructor() {
        super("com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus", [
            { no: 1, name: "presence_status", kind: "enum", T: () => ["com.hamro.jyotish.PresenceStatus", PresenceStatus] },
            { no: 2, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<ConsultantResponse_TimedPresenceStatus>): ConsultantResponse_TimedPresenceStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.presenceStatus = 0;
        message.timestamp = "0";
        if (value !== undefined)
            reflectionMergePartial<ConsultantResponse_TimedPresenceStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConsultantResponse_TimedPresenceStatus): ConsultantResponse_TimedPresenceStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* com.hamro.jyotish.PresenceStatus presence_status */ 1:
                    message.presenceStatus = reader.int32();
                    break;
                case /* int64 timestamp */ 2:
                    message.timestamp = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConsultantResponse_TimedPresenceStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* com.hamro.jyotish.PresenceStatus presence_status = 1; */
        if (message.presenceStatus !== 0)
            writer.tag(1, WireType.Varint).int32(message.presenceStatus);
        /* int64 timestamp = 2; */
        if (message.timestamp !== "0")
            writer.tag(2, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.ConsultantResponse.TimedPresenceStatus
 */
export const ConsultantResponse_TimedPresenceStatus = new ConsultantResponse_TimedPresenceStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllOnlineConsultantResponse$Type extends MessageType<GetAllOnlineConsultantResponse> {
    constructor() {
        super("com.hamro.jyotish.GetAllOnlineConsultantResponse", [
            { no: 1, name: "list", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetAllOnlineConsultantResponse_ConsultantStatus },
            { no: 2, name: "productSKU", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "next_page_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "consultants", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OnlineConsultant }
        ]);
    }
    create(value?: PartialMessage<GetAllOnlineConsultantResponse>): GetAllOnlineConsultantResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.list = [];
        message.productSKU = "";
        message.nextPageCursor = "";
        message.consultants = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllOnlineConsultantResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllOnlineConsultantResponse): GetAllOnlineConsultantResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus list */ 1:
                    message.list.push(GetAllOnlineConsultantResponse_ConsultantStatus.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string productSKU */ 2:
                    message.productSKU = reader.string();
                    break;
                case /* string next_page_cursor */ 3:
                    message.nextPageCursor = reader.string();
                    break;
                case /* repeated com.hamro.jyotish.OnlineConsultant consultants */ 4:
                    message.consultants.push(OnlineConsultant.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllOnlineConsultantResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus list = 1; */
        for (let i = 0; i < message.list.length; i++)
            GetAllOnlineConsultantResponse_ConsultantStatus.internalBinaryWrite(message.list[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string productSKU = 2; */
        if (message.productSKU !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.productSKU);
        /* string next_page_cursor = 3; */
        if (message.nextPageCursor !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.nextPageCursor);
        /* repeated com.hamro.jyotish.OnlineConsultant consultants = 4; */
        for (let i = 0; i < message.consultants.length; i++)
            OnlineConsultant.internalBinaryWrite(message.consultants[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.GetAllOnlineConsultantResponse
 */
export const GetAllOnlineConsultantResponse = new GetAllOnlineConsultantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllOnlineConsultantResponse_ConsultantStatus$Type extends MessageType<GetAllOnlineConsultantResponse_ConsultantStatus> {
    constructor() {
        super("com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus", [
            { no: 1, name: "consultant", kind: "message", T: () => Consultant },
            { no: 2, name: "presence", kind: "enum", T: () => ["com.hamro.jyotish.PresenceStatus", PresenceStatus] },
            { no: 3, name: "no_of_reviews", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetAllOnlineConsultantResponse_ConsultantStatus>): GetAllOnlineConsultantResponse_ConsultantStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.presence = 0;
        message.noOfReviews = "0";
        if (value !== undefined)
            reflectionMergePartial<GetAllOnlineConsultantResponse_ConsultantStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllOnlineConsultantResponse_ConsultantStatus): GetAllOnlineConsultantResponse_ConsultantStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* com.hamro.jyotish.Consultant consultant */ 1:
                    message.consultant = Consultant.internalBinaryRead(reader, reader.uint32(), options, message.consultant);
                    break;
                case /* com.hamro.jyotish.PresenceStatus presence */ 2:
                    message.presence = reader.int32();
                    break;
                case /* int64 no_of_reviews */ 3:
                    message.noOfReviews = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllOnlineConsultantResponse_ConsultantStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* com.hamro.jyotish.Consultant consultant = 1; */
        if (message.consultant)
            Consultant.internalBinaryWrite(message.consultant, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* com.hamro.jyotish.PresenceStatus presence = 2; */
        if (message.presence !== 0)
            writer.tag(2, WireType.Varint).int32(message.presence);
        /* int64 no_of_reviews = 3; */
        if (message.noOfReviews !== "0")
            writer.tag(3, WireType.Varint).int64(message.noOfReviews);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.GetAllOnlineConsultantResponse.ConsultantStatus
 */
export const GetAllOnlineConsultantResponse_ConsultantStatus = new GetAllOnlineConsultantResponse_ConsultantStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllOnlineConsultantRequest$Type extends MessageType<GetAllOnlineConsultantRequest> {
    constructor() {
        super("com.hamro.jyotish.GetAllOnlineConsultantRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "productSKU", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "next_page_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetAllOnlineConsultantRequest>): GetAllOnlineConsultantRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.productSKU = "";
        message.nextPageToken = "";
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<GetAllOnlineConsultantRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllOnlineConsultantRequest): GetAllOnlineConsultantRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string productSKU */ 2:
                    message.productSKU = reader.string();
                    break;
                case /* string next_page_token */ 3:
                    message.nextPageToken = reader.string();
                    break;
                case /* int32 limit */ 4:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllOnlineConsultantRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string productSKU = 2; */
        if (message.productSKU !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.productSKU);
        /* string next_page_token = 3; */
        if (message.nextPageToken !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.nextPageToken);
        /* int32 limit = 4; */
        if (message.limit !== 0)
            writer.tag(4, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.GetAllOnlineConsultantRequest
 */
export const GetAllOnlineConsultantRequest = new GetAllOnlineConsultantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OnlineConsultant$Type extends MessageType<OnlineConsultant> {
    constructor() {
        super("com.hamro.jyotish.OnlineConsultant", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "bio", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rating_count", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "rating", kind: "message", T: () => Rating },
            { no: 7, name: "intro", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "presence_status", kind: "enum", T: () => ["com.hamro.jyotish.PresenceStatus", PresenceStatus] },
            { no: 9, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "total_call_duration", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 11, name: "average_rating", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "joining_since", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 13, name: "years_of_experience", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "profile_banner", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "video", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "thumbnail_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "aspect_ratio", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<OnlineConsultant>): OnlineConsultant {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.image = "";
        message.bio = "";
        message.ratingCount = "0";
        message.intro = "";
        message.presenceStatus = 0;
        message.title = "";
        message.totalCallDuration = "0";
        message.averageRating = 0;
        message.joiningSince = "0";
        message.yearsOfExperience = 0;
        message.profileBanner = "";
        message.video = "";
        message.thumbnailUrl = "";
        message.aspectRatio = "";
        if (value !== undefined)
            reflectionMergePartial<OnlineConsultant>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnlineConsultant): OnlineConsultant {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string image */ 3:
                    message.image = reader.string();
                    break;
                case /* string bio */ 4:
                    message.bio = reader.string();
                    break;
                case /* int64 rating_count */ 5:
                    message.ratingCount = reader.int64().toString();
                    break;
                case /* com.hamro.jyotish.Rating rating */ 6:
                    message.rating = Rating.internalBinaryRead(reader, reader.uint32(), options, message.rating);
                    break;
                case /* string intro */ 7:
                    message.intro = reader.string();
                    break;
                case /* com.hamro.jyotish.PresenceStatus presence_status */ 8:
                    message.presenceStatus = reader.int32();
                    break;
                case /* string title */ 9:
                    message.title = reader.string();
                    break;
                case /* int64 total_call_duration */ 10:
                    message.totalCallDuration = reader.int64().toString();
                    break;
                case /* double average_rating */ 11:
                    message.averageRating = reader.double();
                    break;
                case /* int64 joining_since */ 12:
                    message.joiningSince = reader.int64().toString();
                    break;
                case /* int32 years_of_experience */ 13:
                    message.yearsOfExperience = reader.int32();
                    break;
                case /* string profile_banner */ 14:
                    message.profileBanner = reader.string();
                    break;
                case /* string video */ 15:
                    message.video = reader.string();
                    break;
                case /* string thumbnail_url */ 16:
                    message.thumbnailUrl = reader.string();
                    break;
                case /* string aspect_ratio */ 17:
                    message.aspectRatio = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OnlineConsultant, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string image = 3; */
        if (message.image !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.image);
        /* string bio = 4; */
        if (message.bio !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.bio);
        /* int64 rating_count = 5; */
        if (message.ratingCount !== "0")
            writer.tag(5, WireType.Varint).int64(message.ratingCount);
        /* com.hamro.jyotish.Rating rating = 6; */
        if (message.rating)
            Rating.internalBinaryWrite(message.rating, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string intro = 7; */
        if (message.intro !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.intro);
        /* com.hamro.jyotish.PresenceStatus presence_status = 8; */
        if (message.presenceStatus !== 0)
            writer.tag(8, WireType.Varint).int32(message.presenceStatus);
        /* string title = 9; */
        if (message.title !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.title);
        /* int64 total_call_duration = 10; */
        if (message.totalCallDuration !== "0")
            writer.tag(10, WireType.Varint).int64(message.totalCallDuration);
        /* double average_rating = 11; */
        if (message.averageRating !== 0)
            writer.tag(11, WireType.Bit64).double(message.averageRating);
        /* int64 joining_since = 12; */
        if (message.joiningSince !== "0")
            writer.tag(12, WireType.Varint).int64(message.joiningSince);
        /* int32 years_of_experience = 13; */
        if (message.yearsOfExperience !== 0)
            writer.tag(13, WireType.Varint).int32(message.yearsOfExperience);
        /* string profile_banner = 14; */
        if (message.profileBanner !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.profileBanner);
        /* string video = 15; */
        if (message.video !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.video);
        /* string thumbnail_url = 16; */
        if (message.thumbnailUrl !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.thumbnailUrl);
        /* string aspect_ratio = 17; */
        if (message.aspectRatio !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.aspectRatio);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message com.hamro.jyotish.OnlineConsultant
 */
export const OnlineConsultant = new OnlineConsultant$Type();
/**
 * @generated ServiceType for protobuf service com.hamro.jyotish.UserConsultantService
 */
export const UserConsultantService = new ServiceType("com.hamro.jyotish.UserConsultantService", [
    { name: "GetConsultantById", options: {}, I: GetByIdRequest, O: Consultant },
    { name: "GetAllConsultant", options: {}, I: GetAllConsultantRequest, O: GetAllConsultantResponse },
    { name: "GetLegacyAllConsultant", options: {}, I: Empty, O: GetAllConsultantResponse },
    { name: "GetAllOnlineConsultant", options: {}, I: GetAllOnlineConsultantRequest, O: GetAllOnlineConsultantResponse },
    { name: "SearchConsultant", options: {}, I: SearchConsultantRequest, O: SearchConsultantResponse }
]);
